<a href="https://colab.research.google.com/github/Rohanrathod7/my-ds-labs/blob/main/02_Intermediate%20Python/02_Dictionaries_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Subset and conquer**  
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.

    x = ["a", "b", "c", "d"]
    x[1]
    x[-3] # same result!
Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


Slicing and dicing
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

    my_list[start:end]
The start index will be included, while the end index is not. However, it's also possible not to specify these indexes. If you don't specify the start index, Python figures out that you want to start your slice at the beginning of your list.



In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs);
print(upstairs);


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


In [ ]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[4][1];

In [ ]:
 # Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[-1] = 10.50;


# Change "living room" to "chill zone"
areas[4] = "chill zone";

In [ ]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1
areas_1 = areas + ["poolhouse", 24.5];
areas_2 = areas_1 + ["garage", 15.45];

# Add garage data to areas_1, new list is areas_2


In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Delete the poolhouse items from the list
del areas[10:12];


# Print the updated list
print(areas);

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change this command
areas_copy = areas[:]

# Change areas_copy
areas_copy[0] = 5.0

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [ ]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1));

# Print out length of var1
print(len(var1));

# Convert var2 to an integer: out2
out2 = int(var2);

<class 'list'>
4


In [ ]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second;

# Sort full in descending order: full_sorted
full_sorted = sorted(full);

# Print out full_sorted
print(full_sorted.reverse());

None


In [ ]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place
place_up = place.upper();

# Print out place and place_up
print(place);
print(place_up);


# Print out the number of o's in place
print(place.count("o"));

poolhouse
POOLHOUSE
3


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50));

2
1


In [ ]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5);
areas.append(15.45);


# Print out areas
print(areas);

# Reverse the orders of the elements in areas
areas.reverse();

# Print out areas
print(areas);

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


In [ ]:
# Import the math package
import math

# Calculate C
C = 2 * 0.43 * math.pi;

# Calculate A
A = math.pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [ ]:
# Import pi function of math package
from math import pi

# Calculate C
C = 2 * 0.43 * pi

# Calculate A
A = pi * 0.43 ** 2

print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


### Numpy

In [ ]:
# Import the numpy package as np
import numpy as np

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball);

# Print out type of np_baseball
print(type(np_baseball));

<class 'numpy.ndarray'>


In [ ]:
# Import numpy
import numpy as np

# The 'baseball' variable from cell 'Pjll-YYiKk7_' has the correct 2D structure
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a numpy array from height_in: np_height_in
height_in = [row[0] for row in baseball] # Extract height values from baseball
np_height_in = np.array(height_in);

# Print out np_height_in
print(np_height_in);

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254;

# Print np_height_m
print(np_height_m)

[180 215 210 188]
[4.572  5.461  5.334  4.7752]


In [ ]:
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball);

# Print out the type of np_baseball
print(type(np_baseball));

# Print out the shape of np_baseball
print(np_baseball.shape);

<class 'numpy.ndarray'>
(4, 2)


In [ ]:
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball);

# Print out the shape of np_baseball
print(np_baseball.shape);

(4, 2)


In [ ]:
import numpy as np

np_baseball = np.array(baseball);

# Print out the 50th row of np_baseball
# print(np_baseball[49]);   # Removed as it will cause an IndexError

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1];

# Print out height of 124th player
# print(np_baseball[123,0]);  # Removed as it will cause an IndexError

In [ ]:
import numpy as np

np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
# print(np_baseball + updated); # Removed as 'updated' is not defined

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592]); # Corrected conversion array size

# Print out product of np_baseball and conversion
print(np_baseball * conversion);

[[ 4.572     35.5616128]
 [ 5.461     46.5838984]
 [ 5.334     44.678812 ]
 [ 4.7752    34.1101184]]


In [ ]:
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0];

# Print out the mean of np_height_in
print(np.mean(np_height_in));

# Print out the median of np_height_in
print(np.median(np_height_in));

198.25
199.0


In [ ]:
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height
stddev = np.std(np_baseball[:, 0]);
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1]);

print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
